on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install -U jupyter-book

    - name: Build the book
      run: |
        jupyter-book build .

    - uses: actions/upload-artifact@v2
      with:
        name: _build
        path: _build

  spelling:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: _build
          path: _build

      - uses: goanpeca/setup-miniconda@v1.6.0
        with:
          mamba-version: "*"
          channels: conda-forge
          channel-priority: true

      - shell: bash -l {0}
        run: |
          mamba install -yc conda-forge hunspell-en

      - shell: bash -l {0}
        run: |
          bash .ci_support/check_spelling.sh

  links:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: _build
          path: _build

      - uses: actions/cache@v2
        with:
          path: .pytest-check-links-cache.sqlite
          key: ${{ runner.os }}-link-cache

      - run: |
          pip install -U pytest-check-links requests_cache

      - shell: bash -l {0}
        run: |
          bash .ci_support/check_links.sh
